# Generated by Django 5.1.5 on 2025-01-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0004_house_petsallowed_house_smokersallowed'),
        ('users', '0003_rename_facebok_profile_inquilino_facebook_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True)),
                ('fkHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('fkTenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.inquilino')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True)),
                ('fkRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.room')),
                ('fkTenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.inquilino')),
            ],
        ),
    ]
