# Generated by Django 5.1.5 on 2025-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseOrdersTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserequest',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
