# Generated by Django 5.1.5 on 2025-01-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseOrdersTasks', '0002_alter_houserequest_accepted_and_more'),
        ('houses', '0005_remove_room_isocupied_remove_room_occupiedby'),
        ('users', '0003_rename_facebok_profile_inquilino_facebook_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserequest',
            name='fkHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_requests', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='houserequest',
            name='fkTenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='house_requests', to='users.inquilino'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='fkRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_requests', to='houses.room'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='fkTenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_requests', to='users.inquilino'),
        ),
    ]
