# Generated by Django 5.1.4 on 2024-12-28 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
                ('m2', models.IntegerField()),
                ('house_type', models.CharField(choices=[('Apartment', 'APARTMENT'), ('House', 'HOUSE'), ('Villa', 'VILLA'), ('Studio', 'STUDIO'), ('Duplex', 'DUPLEX')], default='Apartment', max_length=20)),
                ('rooms', models.IntegerField()),
                ('ciudad', models.CharField(max_length=40)),
                ('barrio', models.CharField(max_length=40)),
                ('calle', models.CharField(max_length=50)),
                ('portal', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('fkCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2', models.IntegerField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('isOcupied', models.BooleanField(default=False)),
                ('fkHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('occupiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
