# Generated by Django 5.1.4 on 2025-01-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_image_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='direccion',
        ),
    ]
