# Generated by Django 5.1.5 on 2025-01-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_house_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='petsAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='smokersAllowed',
            field=models.BooleanField(default=False),
        ),
    ]
