# Generated by Django 5.1.5 on 2025-01-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_petsallowed_house_smokersallowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='isOcupied',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupiedBy',
        ),
    ]
