# Generated by Django 5.1.5 on 2025-01-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_remove_room_isocupied_remove_room_occupiedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='petsAllowed',
        ),
        migrations.RemoveField(
            model_name='house',
            name='smokersAllowed',
        ),
    ]
