# Generated by Django 5.1.5 on 2025-02-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_inquilino_facebook_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.inquilino')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='users.inquilino')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fkTenant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_tenant_1', to='users.inquilino')),
                ('fkTenant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_tenant_2', to='users.inquilino')),
            ],
        ),
    ]
