# Generated by Django 5.1.5 on 2025-02-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('users', '0005_inquilino_desiredcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=300)),
                ('fkTenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.inquilino')),
            ],
        ),
    ]
