# Generated by Django 5.1.5 on 2025-02-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
