# Generated by Django 5.1.5 on 2025-02-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_delete_post'),
        ('users', '0005_inquilino_desiredcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fkTenant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posible_match_1', to='users.inquilino')),
                ('fkTenant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posible_match_2', to='users.inquilino')),
            ],
        ),
    ]
