# Generated by Django 5.1.5 on 2025-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
