# Generated by Django 5.1.5 on 2025-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_matches_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
