# Generated by Django 5.1.5 on 2025-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='facebok_profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='instagram_profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
