# Generated by Django 5.1.5 on 2025-01-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inquilino_facebok_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquilino',
            old_name='facebok_profile',
            new_name='facebook_profile',
        ),
    ]
